name: Build and test binaries whether they start

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'client/poetry.lock'
      - 'client/pyoxidizer.bzl'

jobs:
  mac_build:
    uses: ./.github/workflows/dist-build-mac.yaml
    secrets: inherit
  
  mac_binary_test:
    needs: mac_build
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Gefyra tracking config 
        shell: bash
        run: |
          mkdir -p ~/.gefyra
          cd ~/.gefyra
          touch config.ini
          echo "[telemetry]" >> config.ini
          echo "track = False" >> config.ini
      - name: Get version
        working-directory: client/
        run: |
          cat pyproject.toml | grep version -m 1 | awk '{ print "APP_VERSION="substr($3, 2, length($3) -2)}' >> $GITHUB_ENV
      - uses: actions/download-artifact@v3
        with:
          name: gefyra-${{ env.APP_VERSION }}-darwin-universal
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1
      - name: Sanity run Gefyra
        run: |
          ls -la
          chmod u+x ./gefyra
          docker info
          ./gefyra --debug version

  windows_build:
    uses: ./.github/workflows/dist-build-windows.yaml
    secrets: inherit

  windows_binary_test:
    needs: windows_build
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set Gefyra tracking config 
        shell: bash
        run: |
          mkdir -p ~/.gefyra
          cd ~/.gefyra
          touch config.ini
          echo "[telemetry]" >> config.ini
          echo "track = False" >> config.ini
      - name: Determine App Version
        working-directory: client/
        run: |
          python ..\.github\scripts\get_version.py
          echo "${{ env.APP_VERSION }}"
      - uses: actions/download-artifact@v3
        with:
          name: gefyra-${{ env.APP_VERSION }}-windows-x86_64
      - name: Sanity run Gefyra
        run: |
          docker info
          ./gefyra --debug version

  linux_build:
    uses: ./.github/workflows/dist-build-linux.yaml
    secrets: inherit
  
  linux_binary_test:
    needs: linux_build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Gefyra tracking config 
        shell: bash
        run: |
          mkdir -p ~/.gefyra
          cd ~/.gefyra
          touch config.ini
          echo "[telemetry]" >> config.ini
          echo "track = False" >> config.ini
      - name: Get version
        working-directory: client/
        run: |
          cat pyproject.toml | grep version -m 1 | awk '{ print "APP_VERSION="substr($3, 2, length($3) -2)}' >> $GITHUB_ENV
      - uses: actions/download-artifact@v3
        with:
          name: gefyra-${{ env.APP_VERSION }}-linux-amd64
      - name: Sanity run Gefyra
        run: |
          chmod u+x ./gefyra
          docker info
          ./gefyra --debug version
